name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_images:
    name: Build and Push Microservice Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Posts Microservice Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./3-microservices/services/posts
          push: true
          tags: vamshialuwala/posts-service:${{ github.sha }}

      - name: Build and push Threads Microservice Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./3-microservices/services/threads
          push: true
          tags: vamshialuwala/threads-service:${{ github.sha }}

      - name: Build and push Users Microservice Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./3-microservices/services/users
          push: true
          tags: vamshialuwala/users-service:${{ github.sha }}

  # deploy:
  #   needs: build_test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deploying to EC2
  #       uses: actions/checkout@v2
  #       with:
  #        host: {{secrets.EC2_HOST}}
  #        username: {{secrets.EC2_USERNAME}}
  #        key: {{secrets.EC2_PRIVATE_KEY}}
  #        script:
  #           docker pull chetanpatil2003/posts-service:{{ github.sha }}
  #           docker pull chetanpatil2003/threads-service:{{ github.sha }}
  #           docker pull chetanpatil2003/users-service:{{ github.sha }}
  #           docker rm -f posts-service-container
  #           docker rm -f threads-service-container
  #           docker rm -f users-service-container
  #           docker run -d --name posts-service -p 8081:3000 chetanpatil2003/posts-service:{{ github.sha }}
  #           docker run -d --name threads-service -p 8082:3000 chetanpatil2003/threads-service:{{ github.sha }}
  #           docker run -d --name users-service -p 8083:3000 chetanpatil2003/users-service:{{ github.sha }}
